{% set name = "itemadapter" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32c061ec9ab47d5343e8011b268730f48ff632a0192b95292d118b18dbd7687a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - itemadapter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/scrapy/itemadapter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Common interface for different data containers
  description: |
    The ItemAdapter class is a wrapper for data container objects, providing a
    common interface to handle objects of different types in an uniform manner,
    regardless of their underlying implementation.

extra:
  recipe-maintainers:
    - Gallaecio
    - wRAR
    - dangra
    - rmax
