{% set name = "itemadapter" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0431fe5b3f9d95b7e9a20e05789672bc733c173d9989dc9d515ba6b0b9b6a08

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - itemadapter
  requires:
    - python {{ python_min }}
    - pip
    - attrs
    - pydantic <2
    - pytest >=5.4
    - scrapy >=2.0
  source_files:
    - itemadapter
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/scrapy/itemadapter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Common interface for different data containers
  description: |
    The ItemAdapter class is a wrapper for data container objects, providing a
    common interface to handle objects of different types in an uniform manner,
    regardless of their underlying implementation.

extra:
  recipe-maintainers:
    - Gallaecio
    - wRAR
    - dangra
    - rmax
